/*
 * Metal Renderer - Shaders
 *
 * Compiles and manages MSL shaders for the renderer
 */

#import "renderer.h"

#if TARGET_OS_MAC

#import <Metal/Metal.h>

#include <stdio.h>
#include <string.h>

static const char *vertex_shader_msl = 
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct VertexAttribute {\n"
"    float4 position;\n"
"    float4 diffuse;\n"
"    float4 specular;\n"
"    float4 texcoord0;\n"
"    float4 texcoord1;\n"
"    float4 texcoord2;\n"
"    float4 texcoord3;\n"
"    float4 fog;\n"
"    float4 normal;\n"
"};\n"
"\n"
"struct VertexShaderOutput {\n"
"    float4 position [[position]];\n"
"    float4 diffuse;\n"
"    float4 specular;\n"
"    float4 texcoord0;\n"
"    float4 texcoord1;\n"
"    float4 texcoord2;\n"
"    float4 texcoord3;\n"
"    float fog;\n"
"    float4 normal;\n"
"};\n"
"\n"
"vertex VertexShaderOutput vertex_main(uint vertexID [[vertex_id]],\n"
"                                     constant VertexAttribute *vertices [[buffer(0)]]) {\n"
"    VertexShaderOutput out;\n"
"    \n"
"    out.position = vertices[vertexID].position;\n"
"    out.diffuse = vertices[vertexID].diffuse;\n"
"    out.specular = vertices[vertexID].specular;\n"
"    out.texcoord0 = vertices[vertexID].texcoord0;\n"
"    out.texcoord1 = vertices[vertexID].texcoord1;\n"
"    out.texcoord2 = vertices[vertexID].texcoord2;\n"
"    out.texcoord3 = vertices[vertexID].texcoord3;\n"
"    out.fog = vertices[vertexID].fog.x;\n"
"    out.normal = vertices[vertexID].normal;\n"
"    \n"
"    return out;\n"
"}\n";

static const char *fragment_shader_msl =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct FragmentShaderInput {\n"
"    float4 position [[position]];\n"
"    float4 diffuse;\n"
"    float4 specular;\n"
"    float4 texcoord0;\n"
"    float4 texcoord1;\n"
"    float4 texcoord2;\n"
"    float4 texcoord3;\n"
"    float fog;\n"
"    float4 normal;\n"
"};\n"
"\n"
"struct FragmentUniforms {\n"
"    uint texture_enable_mask;\n"
"    uint alpha_func;\n"
"    float alpha_ref;\n"
"    uint alpha_test_enabled;\n"
"    uint combiner_control;\n"
"    uint shader_stage_program;\n"
"    uint other_stage_input;\n"
"    uint final_inputs_0;\n"
"    uint final_inputs_1;\n"
"    uint rgb_inputs[8];\n"
"    uint rgb_outputs[8];\n"
"    uint alpha_inputs[8];\n"
"    uint alpha_outputs[8];\n"
"    uint pad0[3];\n"
"    float4 combiner_consts[18];\n"
"    float4 fog_color;\n"
"    uint tex_modes[4];\n"
"    uint input_tex[4];\n"
"    uint dot_map[4];\n"
"    uint alphakill[4];\n"
"    uint colorkey_mode[4];\n"
"    uint color_key[4];\n"
"    uint color_key_mask[4];\n"
"    uint rect_tex[4];\n"
"    uint tex_cubemap[4];\n"
"    uint dim_tex[4];\n"
"    uint compare_mode[4][4];\n"
"    float4 bump_mat[4];\n"
"    float bump_scale[4];\n"
"    float bump_offset[4];\n"
"};\n"
"\n"
"static uint get_byte(uint value, uint shift) { return (value >> shift) & 0xffu; }\n"
"static uint input_reg(uint value) { return value & 0x0fu; }\n"
"static uint input_chan(uint value) { return value & 0x10u; }\n"
"static uint input_mod(uint value) { return value & 0xe0u; }\n"
"static float3 map_rgb(float3 v, uint mod) {\n"
"    switch (mod) {\n"
"    case 0x00u: return max(v, float3(0.0));\n"
"    case 0x20u: return 1.0 - clamp(v, 0.0, 1.0);\n"
"    case 0x40u: return 2.0 * max(v, float3(0.0)) - 1.0;\n"
"    case 0x60u: return -2.0 * max(v, float3(0.0)) + 1.0;\n"
"    case 0x80u: return max(v, float3(0.0)) - 0.5;\n"
"    case 0xa0u: return -max(v, float3(0.0)) + 0.5;\n"
"    case 0xc0u: return v;\n"
"    case 0xe0u: return -v;\n"
"    default: return v;\n"
"    }\n"
"}\n"
"static float map_alpha(float v, uint mod) {\n"
"    switch (mod) {\n"
"    case 0x00u: return max(v, 0.0);\n"
"    case 0x20u: return 1.0 - clamp(v, 0.0, 1.0);\n"
"    case 0x40u: return 2.0 * max(v, 0.0) - 1.0;\n"
"    case 0x60u: return -2.0 * max(v, 0.0) + 1.0;\n"
"    case 0x80u: return max(v, 0.0) - 0.5;\n"
"    case 0xa0u: return -max(v, 0.0) + 0.5;\n"
"    case 0xc0u: return v;\n"
"    case 0xe0u: return -v;\n"
"    default: return v;\n"
"    }\n"
"}\n"
"static float3 apply_output_rgb(float3 v, uint mapping) {\n"
"    switch (mapping & 0x38u) {\n"
"    case 0x00u: return v;\n"
"    case 0x08u: return v - 0.5;\n"
"    case 0x10u: return v * 2.0;\n"
"    case 0x18u: return (v - 0.5) * 2.0;\n"
"    case 0x20u: return v * 4.0;\n"
"    case 0x30u: return v * 0.5;\n"
"    default: return v;\n"
"    }\n"
"}\n"
"static float apply_output_alpha(float v, uint mapping) {\n"
"    switch (mapping & 0x38u) {\n"
"    case 0x00u: return v;\n"
"    case 0x08u: return v - 0.5;\n"
"    case 0x10u: return v * 2.0;\n"
"    case 0x18u: return (v - 0.5) * 2.0;\n"
"    case 0x20u: return v * 4.0;\n"
"    case 0x30u: return v * 0.5;\n"
"    default: return v;\n"
"    }\n"
"}\n"
"static float4 get_const_reg(constant FragmentUniforms &u, uint reg, uint stage) {\n"
"    uint flags = u.combiner_control >> 8;\n"
"    if (reg == 1u) { return u.combiner_consts[((flags & 0x10u) != 0u || stage == 8u) ? stage * 2u : 0u]; }\n"
"    if (reg == 2u) { return u.combiner_consts[((flags & 0x100u) != 0u || stage == 8u) ? stage * 2u + 1u : 1u]; }\n"
"    return float4(0.0);\n"
"}\n"
"static float4 sample_stage_tex(texture2d<float> tex, sampler s, float4 tc) {\n"
"    if (tex.get_width() == 0 || tex.get_height() == 0) { return float4(0.0); }\n"
"    float w = abs(tc.w) > 1.0e-8 ? tc.w : 1.0;\n"
"    return tex.sample(s, tc.xy / w);\n"
"}\n"
"static float2 normalize_rect(texture2d<float> tex, float2 coord) {\n"
"    return float2(coord.x / float(max((uint)1, tex.get_width())), coord.y / float(max((uint)1, tex.get_height())));\n"
"}\n"
"static bool check_color_key(float4 texel, uint color_key, uint color_key_mask) {\n"
"    uint4 c = uint4(texel * 255.0 + 0.5);\n"
"    uint color = (c.w << 24) | (c.x << 16) | (c.y << 8) | c.z;\n"
"    return (color & color_key_mask) == (color_key & color_key_mask);\n"
"}\n"
"static float sign3(float x) {\n"
"    x *= 255.0;\n"
"    return x >= 128.0 ? (x - 256.0) / 127.0 : x / 127.0;\n"
"}\n"
"static float3 dotmap_value(float4 col, uint mode) {\n"
"    switch (mode & 7u) {\n"
"    case 0u: return col.rgb;\n"
"    case 1u: return float3((col.r * 255.0 - 128.0) / 127.0, (col.g * 255.0 - 128.0) / 127.0, (col.b * 255.0 - 128.0) / 127.0);\n"
"    case 2u: return float3((col.r * 255.0 + 0.5) / 127.5, (col.g * 255.0 + 0.5) / 127.5, (col.b * 255.0 + 0.5) / 127.5);\n"
"    default: return float3(sign3(col.r), sign3(col.g), sign3(col.b));\n"
"    }\n"
"}\n"
"static float2 remap_cube_to_2d(float3 t) {\n"
"    float3 a = abs(t);\n"
"    float2 uv;\n"
"    if (a.x > a.y && a.x > a.z) { uv = t.x > 0.0 ? float2(-t.z, t.y) : float2(t.z, t.y); uv /= max(a.x, 1.0e-8); }\n"
"    else if (a.y > a.x && a.y > a.z) { uv = t.y > 0.0 ? float2(t.x, -t.z) : float2(t.x, t.z); uv /= max(a.y, 1.0e-8); }\n"
"    else { uv = t.z > 0.0 ? float2(t.x, t.y) : float2(-t.x, t.y); uv /= max(a.z, 1.0e-8); }\n"
"    return uv;\n"
"}\n"
"static float4 sample_texture_stage(uint stage, float4 tc, constant FragmentUniforms &u, texture2d<float> colorTexture0, texture2d<float> colorTexture1, texture2d<float> colorTexture2, texture2d<float> colorTexture3, sampler textureSampler0, sampler textureSampler1, sampler textureSampler2, sampler textureSampler3) {\n"
"    float4 result = float4(0.0, 0.0, 0.0, 1.0);\n"
"    float2 uv = tc.xy;\n"
"    float w = abs(tc.w) > 1.0e-8 ? tc.w : 1.0;\n"
"    switch (stage) {\n"
"    case 0u:\n"
"        if (u.rect_tex[0] != 0u) { uv = normalize_rect(colorTexture0, uv / w); } else { uv /= w; }\n"
"        result = colorTexture0.get_width() > 0 ? colorTexture0.sample(textureSampler0, uv) : result;\n"
"        break;\n"
"    case 1u:\n"
"        if (u.rect_tex[1] != 0u) { uv = normalize_rect(colorTexture1, uv / w); } else { uv /= w; }\n"
"        result = colorTexture1.get_width() > 0 ? colorTexture1.sample(textureSampler1, uv) : result;\n"
"        break;\n"
"    case 2u:\n"
"        if (u.rect_tex[2] != 0u) { uv = normalize_rect(colorTexture2, uv / w); } else { uv /= w; }\n"
"        result = colorTexture2.get_width() > 0 ? colorTexture2.sample(textureSampler2, uv) : result;\n"
"        break;\n"
"    case 3u:\n"
"        if (u.rect_tex[3] != 0u) { uv = normalize_rect(colorTexture3, uv / w); } else { uv /= w; }\n"
"        result = colorTexture3.get_width() > 0 ? colorTexture3.sample(textureSampler3, uv) : result;\n"
"        break;\n"
"    }\n"
"    return result;\n"
"}\n"
"static float4 resolve_stage_tex(uint stage, constant FragmentUniforms &u, float4 pT0, float4 pT1, float4 pT2, float4 pT3, float4 t0_prev, float4 t1_prev, float4 t2_prev, float4 t3_prev, texture2d<float> colorTexture0, texture2d<float> colorTexture1, texture2d<float> colorTexture2, texture2d<float> colorTexture3, sampler textureSampler0, sampler textureSampler1, sampler textureSampler2, sampler textureSampler3) {\n"
"    if ((u.texture_enable_mask & (1u << stage)) == 0u) { return float4(0.0, 0.0, 0.0, 1.0); }\n"
"    float4 coords = stage == 0u ? pT0 : (stage == 1u ? pT1 : (stage == 2u ? pT2 : pT3));\n"
"    uint mode = u.tex_modes[stage];\n"
"    uint input_tex = u.input_tex[stage];\n"
"    float4 input_sample = input_tex == 0u ? t0_prev : (input_tex == 1u ? t1_prev : (input_tex == 2u ? t2_prev : t3_prev));\n"
"    switch (mode) {\n"
"    case 0u: return float4(0.0, 0.0, 0.0, 1.0);\n"
"    case 1u: return sample_texture_stage(stage, float4(coords.xy, 0.0, coords.w), u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    case 2u: return sample_texture_stage(stage, coords, u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    case 3u: return sample_texture_stage(stage, float4(remap_cube_to_2d(coords.xyz), 0.0, 1.0), u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    case 4u: return coords;\n"
"    case 5u: {\n"
"        bool discard = false;\n"
"        if ((coords.x >= 0.0) == (u.compare_mode[stage][0] != 0u)) discard = true;\n"
"        if ((coords.y >= 0.0) == (u.compare_mode[stage][1] != 0u)) discard = true;\n"
"        if ((coords.z >= 0.0) == (u.compare_mode[stage][2] != 0u)) discard = true;\n"
"        if ((coords.w >= 0.0) == (u.compare_mode[stage][3] != 0u)) discard = true;\n"
"        if (discard) { discard_fragment(); }\n"
"        return float4(0.0);\n"
"    }\n"
"    case 6u: {\n"
"        float2 dsdt = float2(sign3(input_sample.b), sign3(input_sample.g));\n"
"        float2 offs = float2(dot(float2(u.bump_mat[stage].x, u.bump_mat[stage].y), dsdt), dot(float2(u.bump_mat[stage].z, u.bump_mat[stage].w), dsdt));\n"
"        return sample_texture_stage(stage, float4(coords.xy + offs, 0.0, coords.w), u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    }\n"
"    case 7u: {\n"
"        float3 dsdtl = float3(sign3(input_sample.b), sign3(input_sample.g), input_sample.r);\n"
"        float2 offs = float2(dot(float2(u.bump_mat[stage].x, u.bump_mat[stage].y), dsdtl.xy), dot(float2(u.bump_mat[stage].z, u.bump_mat[stage].w), dsdtl.xy));\n"
"        return sample_texture_stage(stage, float4(coords.xy + offs, 0.0, coords.w), u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3) * (u.bump_scale[stage] * dsdtl.z + u.bump_offset[stage]);\n"
"    }\n"
"    case 15u: return sample_texture_stage(stage, float4(input_sample.ar, 0.0, 1.0), u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    case 16u: return sample_texture_stage(stage, float4(input_sample.gb, 0.0, 1.0), u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    case 17u: { float d = dot(coords.xyz, dotmap_value(input_sample, u.dot_map[stage])); return float4(d); }\n"
"    default: return sample_texture_stage(stage, coords, u, colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3);\n"
"    }\n"
"}\n"
"static float4 postprocess_stage_tex(uint stage, float4 t, constant FragmentUniforms &u) {\n"
"    if (u.alphakill[stage] != 0u && t.a == 0.0) { discard_fragment(); }\n"
"    if (u.colorkey_mode[stage] != 0u && check_color_key(t, u.color_key[stage], u.color_key_mask[stage])) {\n"
"        if (u.colorkey_mode[stage] == 3u) { discard_fragment(); }\n"
"        else if (u.colorkey_mode[stage] == 1u) { t.a = 0.0; }\n"
"        else if (u.colorkey_mode[stage] == 2u) { t = float4(0.0); }\n"
"    }\n"
"    return t;\n"
"}\n"
"static float4 get_reg(uint reg, uint stage, constant FragmentUniforms &u, float4 v0, float4 v1, float4 t0, float4 t1, float4 t2, float4 t3, float4 r0, float4 r1, float3 ef_prod) {\n"
"    switch (reg) {\n"
"    case 0u: return float4(0.0);\n"
"    case 1u: case 2u: return get_const_reg(u, reg, stage);\n"
"    case 3u: return float4(u.fog_color.rgb, clamp(u.fog_color.a * clamp(v0.a, 0.0, 1.0) + (1.0 - u.fog_color.a) * clamp(v1.a, 0.0, 1.0), 0.0, 1.0));\n"
"    case 4u: return v0;\n"
"    case 5u: return v1;\n"
"    case 8u: return t0;\n"
"    case 9u: return t1;\n"
"    case 10u: return t2;\n"
"    case 11u: return t3;\n"
"    case 12u: return r0;\n"
"    case 13u: return r1;\n"
"    case 14u: {\n"
"        bool inv_v1 = (u.final_inputs_1 & 0x40u) != 0u;\n"
"        bool inv_r0 = (u.final_inputs_1 & 0x20u) != 0u;\n"
"        bool clamp_sum = (u.final_inputs_1 & 0x80u) != 0u;\n"
"        float3 s = (inv_v1 ? (1.0 - v1.rgb) : v1.rgb) + (inv_r0 ? (1.0 - r0.rgb) : r0.rgb);\n"
"        if (clamp_sum) { s = clamp(s, 0.0, 1.0); }\n"
"        return float4(s, 0.0);\n"
"    }\n"
"    case 15u: return float4(ef_prod, 0.0);\n"
"    default: return float4(0.0);\n"
"    }\n"
"}\n"
"static float3 fetch_rgb(uint packed, uint stage, constant FragmentUniforms &u, float4 v0, float4 v1, float4 t0, float4 t1, float4 t2, float4 t3, float4 r0, float4 r1, float3 ef_prod) {\n"
"    float4 reg = get_reg(input_reg(packed), stage, u, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"    float3 src = input_chan(packed) == 0x10u ? reg.aaa : reg.rgb;\n"
"    return map_rgb(src, input_mod(packed));\n"
"}\n"
"static float fetch_alpha(uint packed, uint stage, constant FragmentUniforms &u, float4 v0, float4 v1, float4 t0, float4 t1, float4 t2, float4 t3, float4 r0, float4 r1, float3 ef_prod) {\n"
"    float4 reg = get_reg(input_reg(packed), stage, u, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"    float src = input_chan(packed) == 0x10u ? reg.a : reg.b;\n"
"    return map_alpha(src, input_mod(packed));\n"
"}\n"
"static void write_rgb(uint reg, float3 value, bool blue_to_alpha, thread float4 &v0, thread float4 &v1, thread float4 &t0, thread float4 &t1, thread float4 &t2, thread float4 &t3, thread float4 &r0, thread float4 &r1) {\n"
"    thread float4 *dst = nullptr;\n"
"    switch (reg) { case 4u: dst=&v0; break; case 5u: dst=&v1; break; case 8u: dst=&t0; break; case 9u: dst=&t1; break; case 10u: dst=&t2; break; case 11u: dst=&t3; break; case 12u: dst=&r0; break; case 13u: dst=&r1; break; default: break; }\n"
"    if (dst != nullptr) { dst->rgb = value; if (blue_to_alpha) { dst->a = value.b; } }\n"
"}\n"
"static void write_alpha(uint reg, float value, thread float4 &v0, thread float4 &v1, thread float4 &t0, thread float4 &t1, thread float4 &t2, thread float4 &t3, thread float4 &r0, thread float4 &r1) {\n"
"    thread float4 *dst = nullptr;\n"
"    switch (reg) { case 4u: dst=&v0; break; case 5u: dst=&v1; break; case 8u: dst=&t0; break; case 9u: dst=&t1; break; case 10u: dst=&t2; break; case 11u: dst=&t3; break; case 12u: dst=&r0; break; case 13u: dst=&r1; break; default: break; }\n"
"    if (dst != nullptr) { dst->a = value; }\n"
"}\n"
"static bool alpha_test_pass(float alpha, constant FragmentUniforms &u) {\n"
"    if (u.alpha_test_enabled == 0) {\n"
"        return true;\n"
"    }\n"
"    switch (u.alpha_func) {\n"
"    case 1: return false;\n"
"    case 2: return alpha < u.alpha_ref;\n"
"    case 3: return alpha == u.alpha_ref;\n"
"    case 4: return alpha <= u.alpha_ref;\n"
"    case 5: return alpha > u.alpha_ref;\n"
"    case 6: return alpha != u.alpha_ref;\n"
"    case 7: return alpha >= u.alpha_ref;\n"
"    default: return true;\n"
"    }\n"
"}\n"
"\n"
"fragment float4 fragment_main(FragmentShaderInput in [[stage_in]],\n"
"                            constant FragmentUniforms &uniforms [[buffer(0)]],\n"
"                            texture2d<float> colorTexture0 [[texture(0)]],\n"
"                            texture2d<float> colorTexture1 [[texture(1)]],\n"
"                            texture2d<float> colorTexture2 [[texture(2)]],\n"
"                            texture2d<float> colorTexture3 [[texture(3)]],\n"
"                            sampler textureSampler0 [[sampler(0)]],\n"
"                            sampler textureSampler1 [[sampler(1)]],\n"
"                            sampler textureSampler2 [[sampler(2)]],\n"
"                            sampler textureSampler3 [[sampler(3)]]) {\n"
"    float4 v0 = in.diffuse;\n"
"    float4 v1 = in.specular;\n"
"    float4 pFog = float4(uniforms.fog_color.rgb, clamp(in.fog, 0.0, 1.0));\n"
"    float4 t0 = postprocess_stage_tex(0u, resolve_stage_tex(0u, uniforms, in.texcoord0, in.texcoord1, in.texcoord2, in.texcoord3, float4(0.0), float4(0.0), float4(0.0), float4(0.0), colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3), uniforms);\n"
"    float4 t1 = postprocess_stage_tex(1u, resolve_stage_tex(1u, uniforms, in.texcoord0, in.texcoord1, in.texcoord2, in.texcoord3, t0, float4(0.0), float4(0.0), float4(0.0), colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3), uniforms);\n"
"    float4 t2 = postprocess_stage_tex(2u, resolve_stage_tex(2u, uniforms, in.texcoord0, in.texcoord1, in.texcoord2, in.texcoord3, t0, t1, float4(0.0), float4(0.0), colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3), uniforms);\n"
"    float4 t3 = postprocess_stage_tex(3u, resolve_stage_tex(3u, uniforms, in.texcoord0, in.texcoord1, in.texcoord2, in.texcoord3, t0, t1, t2, float4(0.0), colorTexture0, colorTexture1, colorTexture2, colorTexture3, textureSampler0, textureSampler1, textureSampler2, textureSampler3), uniforms);\n"
"    float4 r0 = float4(0.0);\n"
"    float4 r1 = float4(0.0);\n"
"    uint num_stages = uniforms.combiner_control & 0xffu;\n"
"    for (uint i = 0u; i < num_stages && i < 8u; i++) {\n"
"        float3 ef_prod = float3(0.0);\n"
"        float3 a = fetch_rgb(get_byte(uniforms.rgb_inputs[i], 24u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 b = fetch_rgb(get_byte(uniforms.rgb_inputs[i], 16u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 c = fetch_rgb(get_byte(uniforms.rgb_inputs[i], 8u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 d = fetch_rgb(get_byte(uniforms.rgb_inputs[i], 0u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 ab = ((uniforms.rgb_outputs[i] >> 12) & 0x2u) != 0u ? float3(dot(a, b)) : (a * b);\n"
"        float3 cd = ((uniforms.rgb_outputs[i] >> 12) & 0x1u) != 0u ? float3(dot(c, d)) : (c * d);\n"
"        float3 abm = clamp(apply_output_rgb(ab, uniforms.rgb_outputs[i] >> 12), -1.0, 1.0);\n"
"        float3 cdm = clamp(apply_output_rgb(cd, uniforms.rgb_outputs[i] >> 12), -1.0, 1.0);\n"
"        float3 muxsum = (((uniforms.rgb_outputs[i] >> 12) & 0x4u) != 0u) ? (((uniforms.combiner_control >> 8) & 0x1u) != 0u ? ((r0.a >= 0.5) ? cdm : abm) : ((((uint)(r0.a * 255.0)) & 1u) != 0u ? cdm : abm)) : clamp(apply_output_rgb(ab + cd, uniforms.rgb_outputs[i] >> 12), -1.0, 1.0);\n"
"        write_rgb((uniforms.rgb_outputs[i] >> 4) & 0x0fu, abm, ((uniforms.rgb_outputs[i] >> 12) & 0x80u) != 0u, v0, v1, t0, t1, t2, t3, r0, r1);\n"
"        write_rgb(uniforms.rgb_outputs[i] & 0x0fu, cdm, ((uniforms.rgb_outputs[i] >> 12) & 0x40u) != 0u, v0, v1, t0, t1, t2, t3, r0, r1);\n"
"        write_rgb((uniforms.rgb_outputs[i] >> 8) & 0x0fu, muxsum, false, v0, v1, t0, t1, t2, t3, r0, r1);\n"
"        float aa = fetch_alpha(get_byte(uniforms.alpha_inputs[i], 24u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float bb = fetch_alpha(get_byte(uniforms.alpha_inputs[i], 16u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float cc = fetch_alpha(get_byte(uniforms.alpha_inputs[i], 8u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float dd = fetch_alpha(get_byte(uniforms.alpha_inputs[i], 0u), i, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float ab_a = apply_output_alpha(aa * bb, uniforms.alpha_outputs[i] >> 12);\n"
"        float cd_a = apply_output_alpha(cc * dd, uniforms.alpha_outputs[i] >> 12);\n"
"        float mux_a = (((uniforms.alpha_outputs[i] >> 12) & 0x4u) != 0u) ? ((((uniforms.combiner_control >> 8) & 0x1u) != 0u ? (r0.a >= 0.5) : ((((uint)(r0.a * 255.0)) & 1u) != 0u)) ? cd_a : ab_a) : apply_output_alpha(aa * bb + cc * dd, uniforms.alpha_outputs[i] >> 12);\n"
"        write_alpha((uniforms.alpha_outputs[i] >> 4) & 0x0fu, clamp(ab_a, -1.0, 1.0), v0, v1, t0, t1, t2, t3, r0, r1);\n"
"        write_alpha(uniforms.alpha_outputs[i] & 0x0fu, clamp(cd_a, -1.0, 1.0), v0, v1, t0, t1, t2, t3, r0, r1);\n"
"        write_alpha((uniforms.alpha_outputs[i] >> 8) & 0x0fu, clamp(mux_a, -1.0, 1.0), v0, v1, t0, t1, t2, t3, r0, r1);\n"
"    }\n"
"    float4 color = r0;\n"
"    if (uniforms.final_inputs_0 != 0u || uniforms.final_inputs_1 != 0u) {\n"
"        float3 ef_prod = fetch_rgb(get_byte(uniforms.final_inputs_1, 24u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, float3(0.0)) * fetch_rgb(get_byte(uniforms.final_inputs_1, 16u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, float3(0.0));\n"
"        float3 a = fetch_rgb(get_byte(uniforms.final_inputs_0, 24u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 b = fetch_rgb(get_byte(uniforms.final_inputs_0, 16u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 c = fetch_rgb(get_byte(uniforms.final_inputs_0, 8u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float3 d = fetch_rgb(get_byte(uniforms.final_inputs_0, 0u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        float g = fetch_alpha(get_byte(uniforms.final_inputs_1, 8u), 8u, uniforms, v0, v1, t0, t1, t2, t3, r0, r1, ef_prod);\n"
"        color = float4(d + mix(c, b, a), g);\n"
"    }\n"
"    color = clamp(color, 0.0, 1.0);\n"
"    if (!alpha_test_pass(color.a, uniforms)) {\n"
"        discard_fragment();\n"
"    }\n"
"    \n"
"    return color;\n"
"}\n";

static const char *texture_fragment_shader_msl =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct TextureVertexOutput {\n"
"    float4 position [[position]];\n"
"    float2 texcoord;\n"
"};\n"
"\n"
"fragment float4 texture_fragment(TextureVertexOutput in [[stage_in]],\n"
"                               texture2d<float> colorTexture [[texture(0)]],\n"
"                               sampler textureSampler [[sampler(0)]]) {\n"
"    return colorTexture.sample(textureSampler, in.texcoord);\n"
"}\n";

void pgraph_mtl_shaders_init(PGRAPHMTLState *r)
{
    fprintf(stderr, "Metal: Initializing shaders\n");
    
    if (!r->device) {
        fprintf(stderr, "Metal: No device for shader init\n");
        r->initialized = false;
        return;
    }
    
    id<MTLDevice> device = (__bridge id<MTLDevice>)r->device;
    NSError *error = nil;
    
    NSString *combinedSrc = [NSString stringWithUTF8String:vertex_shader_msl];
    combinedSrc = [combinedSrc stringByAppendingString:[NSString stringWithUTF8String:fragment_shader_msl]];
    combinedSrc = [combinedSrc stringByAppendingString:[NSString stringWithUTF8String:texture_fragment_shader_msl]];
    
    id<MTLLibrary> library = [device newLibraryWithSource:combinedSrc options:nil error:&error];
    if (error) {
        fprintf(stderr, "Metal: Failed to compile shaders: %s\n", [[error localizedDescription] UTF8String]);
        r->initialized = false;
        return;
    }
    
    r->shader_library = (__bridge void *)library;
    
    fprintf(stderr, "Metal: Shaders compiled successfully\n");
}

void pgraph_mtl_shaders_destroy(PGRAPHMTLState *r)
{
    if (r->shader_library) {
        r->shader_library = nil;
    }
}

#endif
